"""empty message

Revision ID: b9ccd5426c22
Revises: 473c818384f8
Create Date: 2020-05-21 23:03:35.047816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ccd5426c22'
down_revision = '473c818384f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('us_infections', sa.Column('cwbined_key', sa.String(), nullable=True))
    op.drop_column('us_infections', 'combined_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('us_infections', sa.Column('combined_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('us_infections', 'cwbined_key')
    # ### end Alembic commands ###
