"""empty message

Revision ID: 383b3533f07d
Revises: b9ccd5426c22
Create Date: 2020-05-21 23:04:14.607643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383b3533f07d'
down_revision = 'b9ccd5426c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.add_column('us_infections', sa.Column('combined_key', sa.String(), nullable=True))
    op.drop_column('us_infections', 'cwbined_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('us_infections', sa.Column('cwbined_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('us_infections', 'combined_key')
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    # ### end Alembic commands ###
