"""empty message

Revision ID: 473c818384f8
Revises: d6f19db91f01
Create Date: 2020-05-21 23:02:37.699361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473c818384f8'
down_revision = 'd6f19db91f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_us_infections_index', table_name='us_infections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_us_infections_index', 'us_infections', ['index'], unique=False)
    op.drop_table('books')
    # ### end Alembic commands ###
